version: '3.8'

services:
  backend:
    build: ./banksajt-backend
    ports:
      - '3001:3001'
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build: ./banksajt-frontend
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - backend

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
